### ISSUE TITLE
anchors in flatdoc

### ISSUE THREAD

**Issue by chrisbrowneanu** [rstacruz/flatdoc#21]
Loving Flatdoc. Hopefully someone can help.

I'm having trouble with anchors in Flatdoc - for example: http://ricostacruz.com/flatdoc/#javascript-hooks doesn't take you to #javascript-hooks (unless you're already on the page)

I'm guessing that it's because the anchor doesn't exist in the page when it's loaded, but it would be great if it could be picked up somehow once loaded.

**Comment by rstacruz** [comment]
Fixed, and will be released under 0.8.5 soon, thanks to @malthe.

**Comment by chrisbrowneanu** [comment]
That's great. Thanks - and hopefully others will find it super-useful too.

**Comment by Wenzil** [comment]
The fix works in Firefox but not in Chrome (tested with version 40.0.2214.111)

**Comment by malthe** [comment]
@Wenzil do you have an example you can link to where it doesn't work?

**Comment by Wenzil** [comment]
Weird, I had tried with the link from the original post as well as my own site but it all works without a hitch now. Maybe Chrome was being unresponsive on my end for some reason. Nice!

Edit: Just realized the link in the original post is outdated so that's why that didn't work. The correct link would be http://ricostacruz.com/flatdoc/#customizing-basic-javascript-hooks. I probably messed up my own link when I first tried on my site. Anyway all is good now!
